language: php

php:
  - 7.2
  - 7.1
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh
  - composer validate

install:
  - composer --ignore-platform-reqs --prefer-dist install

script:
  - vendor/bin/phan
  - ./test
